# Generated by Django 5.2 on 2025-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_product_category_product_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
    ]
