# Generated by Django 5.2 on 2025-05-06 12:12

import apps.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_adminuser_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, storage=apps.storage_backends.StaticStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
